spring:
    application:
        name: service-zuul
    cloud:
        config:
            label: master
            profile: dev
            discovery:
                enabled: true
                serviceId: config-server