
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        lease-expiration-duration-in-seconds: 2
        lease-renewal-interval-in-seconds: 1
feign:
    hystrix:
        enabled: true
server:
    port: 8772
spring:
    application:
        name: service-register
hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000

