server:
  port: 8773
spring:
  application:
    name: service-message
eureka:
  instance:
    #每一秒想注册中心发送一次心跳检测
    lease-renewal-interval-in-seconds: 1
    #如果两秒钟没有发送心跳检测,则证明该服务已死亡
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

aliyun:
  accessKeyId: ***************
  accessKeySecret: ****************
  regionId: default
  domain: dysmsapi.aliyuncs.com
  version: 2017-05-25
  action: SendSms
  SignName: clouddemo
  TemplateCode: SMS_173348277

