server:
  port: 8770

spring:
  application:
    name: service-mail
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
  mail:
    host: smtp.qq.com
    username: 821319695@qq.com
      #QQ邮箱的授权码
    password: nlmosrgfjtrqbcbh
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  instance:
    #每一秒想注册中心发送一次心跳检测
    lease-renewal-interval-in-seconds: 1
    #如果两秒钟没有发送心跳检测,则证明该服务已死亡
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/